### ISSUE TITLE
how to implement the respond to 307 Temporary Redirect

### ISSUE THREAD

**Issue by OnNeNousDitPasTout** [vla/FastHttpRequest#1]
Hi, i want to use your assembly to make some test with the Docs-master\aspnetcore\tutorials\first-mongo-app project in netCore documentation ("Download the ASP.NET repository zip file." at https://docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-2.2). 
The server respond 307, how i turn over to get the json books list (with a Navigator all is good).

This is my code : 

string url = "http://localhost:5000/api/books";

var res = HttpHelper.Get(url);
Console.WriteLine("Résultat " + res);

if i scan res with debugger i can see the 307 respond of the server.

i have try with task Invoker or Async Invoker , they have failed. 

  Thanks for help

**Comment by vla** [comment]
Hello, thank you very much for the problem you found.This problem has been fixed. Please try again.

**Comment by OnNeNousDitPasTout** [comment]
Thanks, it's good now 💯
