### ISSUE TITLE
trouble with invalid certificate

### ISSUE THREAD

**Issue by OnNeNousDitPasTout** [vla/FastHttpRequest#2]
hi again JohnWu, my serveur don't have a valid certificate. I can force the Navigator to pass through.
But, how can i do that with FastHttpResquest ?
DId FastHttpResquest support https ?

Thanks for your help.

    Tangi

**Comment by vla** [comment]
@OnNeNousDitPasTout 
```cs
  HttpHelper.Request(new HttpHelper.HttpParam
            {
                URL = "htts://xxxxxxxxxxxxx",
                Method = HttpHelper.HttpVerb.Get,
                RemoteCertificateValidationCallback = OnRemoteCertificateValidationCallback//Skip SSL validation
            });

 private bool OnRemoteCertificateValidationCallback(
            object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
        {
            //skip valid
            return true;
        }
````

**Comment by OnNeNousDitPasTout** [comment]
Ok i make like you say and it 's good (this is my code) :

`HttpHelper.Request(new HttpHelper.HttpParam {
											URL = url
											,Method = HttpHelper.HttpVerb.Get
											,RemoteCertificateValidationCallback = OnRemoteCertificateValidationCallback
											}
										, (c) =>
											{
												var sr = new StreamReader(c.Result);
												Console.WriteLine("Get : " + sr.ReadToEnd());
											});`

just a tip : i have to make a Console.ReadKey() after that, else the program end before the display or the server respond.
Perhaps it would be beter to mark the method with async ?

Thanks for your help already.
